# --- Global Inputs ---
aoi_shapefile: "data/aoi.shp"
power_points_shapefile: "data/power_points.shp"
power_lines_shapefile: "data/power_lines.shp"
sample_points_per_line: 10
output_dir: "output"

# --- Hazard Layers ---
hazards:
  pluvial_flood:
    active: false
    raster: data/plu.tif
    threshold: 4

  fluvial_flood:
    active: false
    raster: data/flu.tif
    threshold: 6

  landslide:
    active: false
    raster: data/landslide.tif
    threshold: 0.3

  earthquick:
    active: false
    raster: data/seismic.tif
    threshold: 0.15

  wildfire:
    active: false
    input_dir: data/wildfire_shapefiles

  drought:
    active: true
    start_year: 2022
    start_month: 6
    end_year: 2023
    end_month: 8
