# === Global Configuration ===

# Path to the Area of Interest (AOI) shapefile
aoi: "../data/tajik/aoi.shp"

# Path to infrastructure 
infrastructure_inputs:
  points:
    transformer: "../data/tajik/TJK_Transformers.shp"
    tower: "../data/tajik/TJK_Towers.shp"
    substations: "../data/tajik/TJK_Substations.shp"
    existing: null      

  lines:
    lv: "../data/tajik/TJK_LV_Lines.shp"
    hv: "../data/tajik/TJK_HV_Lines.shp"
    existing: null


# Directory where all outputs will be saved
output_dir: "../data/testoct"


# === Hazard Layers Configuration ===
hazards:

  pluvial_flood:
    active: true
    input: "../data/tajik/plu.tif"        
    threshold: 4                

  fluvial_flood:
    active: true
    input: "../data/tajik/flu.tif"       
    threshold: 6

  landslide:
    active: true
    input: "../data/landslide.tif"  
    threshold: 0.3

  earthquake:
    active: true
    input: "../data/earthquacke.tif"   
    threshold: 0.3

  wildfire:
    active: false
    input: "/Users/nassimdekkar/Downloads/GLOBFIRE_burned_area_full_dataset_2002_2023"  # Directory containing wildfire shapefiles
    threshold: 0.5  

  heat:
    active: true
    input: "../data/heat_tajikistan_2010_2024.nc"  # NetCDF file for heat hazard (e.g. Tmax)
    threshold: 35

  cold:
    active: true
    input: "../data/hazards/cold/TNn_mean_2010_2024.tif"
    threshold: -20