# === Global Configuration ===

# Path to the Area of Interest (AOI) shapefile
aoi: "../data/tajik/aoi.shp"

# Path to infrastructure points (e.g. substations, power plants)
infrastructure_inputs:
  points:
    transformer: "../data/tajik/TJK_Transformers.shp"
    tower: "../data/tajik/TJK_Towers.shp"
    substations: "../data/tajik/TJK_Substations.shp"
    existing: null      

  lines:
    lv: "../data/tajik/TJK_LV_Lines.shp"
    hv: "../data/tajik/TJK_HV_Lines.shp"
    existing: null


# Directory where all outputs will be saved
output_dir: "../data/heataj"


# === Hazard Layers Configuration ===
hazards:

  pluvial_flood:
    active: false
    input: "../data/tajik/plu.tif"        # Raster input for pluvial flood
    threshold: 4                 # Threshold value for exposure

  fluvial_flood:
    active: false
    input: "../data/tajik/flu.tif"        # Raster input for fluvial flood
    threshold: 6

  landslide:
    active: false
    input: "../data/landslide.tif"  # Raster input for landslide
    threshold: 0.3

  earthquake:
    active: false
    input: "../data/earthquacke.tif"    # Raster input for seismic hazard
    threshold: 0.5

  wildfire:
    active: false
    input: "/Users/nassimdekkar/Downloads/GLOBFIRE_burned_area_full_dataset_2002_2023"  # Directory containing wildfire shapefiles
    threshold: 0.5  

  heat:
    active: true
    input: "../data/heat_tajikistan_2010_2024.nc"  # NetCDF file for heat hazard (e.g. Tmax)
    threshold: 35