aoi_shapefile: "data/aoi.shp"
power_points_shapefile: "data/power_points.shp"
power_lines_shapefile: "data/power_lines.shp"

hazards:
  FLOOD:
    active: true
    raster: "data/flood.tif"
    threshold: 0.0

  LANDSLIDE:
    active: false
    raster: "data/"
    threshold: 15.0

  FIRE:
    active: false
    raster: "data/"
    threshold: 0.5

sample_points_per_line: 10
output_dir: "output"