country_shapefile: "data/country.shp"
power_points_shapefile: "data/power_points.shp"
power_lines_shapefile: "data/power_lines.shp"
flood_raster: "data/flood.tif"

output_points: "output/power_points_exposure.shp"
output_lines: "output/power_lines_exposure.shp"

sample_points_per_line: 10
flood_threshold: 0.0
